name: thesis_2
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2022.12.7=h5b45459_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - debugpy=1.6.7=py311h12c1d0e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - importlib-metadata=6.3.0=pyha770c72_0
  - importlib_metadata=6.3.0=hd8ed1ab_0
  - ipykernel=6.22.0=pyh025b116_0
  - ipython=8.12.0=pyh08f2357_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py311h1ea47a8_0
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.2=h8ffe710_5
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.40.0=hcfcfb64_0
  - libzlib=1.2.13=hcfcfb64_4
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=3.1.0=hcfcfb64_0
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.0.1=pyhd8ed1ab_0
  - platformdirs=3.2.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.4=py311ha68e1ae_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.15.0=pyhd8ed1ab_0
  - python=3.11.3=h2628c8c_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pywin32=304=py311h12c1d0e_2
  - pyzmq=25.0.2=py311h7b3f143_0
  - setuptools=67.6.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - tornado=6.2=py311ha68e1ae_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.3=hb6edc58_10
  - vs2015_runtime=14.34.31931=h4c5c07a_10
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - pip:
    - absl-py==1.4.0
    - appdirs==1.4.4
    - cachetools==5.3.0
    - certifi==2022.12.7
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cloudpickle==2.2.1
    - docker-pycreds==0.4.0
    - farama-notifications==0.0.4
    - filelock==3.9.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.17.3
    - google-auth-oauthlib==1.0.0
    - grpcio==1.53.0
    - gymnasium==0.28.1
    - idna==3.4
    - jax-jumpy==1.0.0
    - jinja2==3.1.2
    - markdown==3.4.3
    - markupsafe==2.1.2
    - mpmath==1.2.1
    - networkx==3.0
    - numpy==1.24.1
    - oauthlib==3.2.2
    - pathtools==0.1.2
    - pillow==9.3.0
    - protobuf==4.22.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyyaml==6.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - sentry-sdk==1.19.1
    - setproctitle==1.3.2
    - smmap==5.0.0
    - sympy==1.11.1
    - tensorboard==2.12.2
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - torch==2.0.0+cu117
    - torchaudio==2.0.1+cu117
    - torchvision==0.15.1+cu117
    - urllib3==1.26.13
    - wandb==0.14.2
    - werkzeug==2.2.3
prefix: C:\Users\h4rip\anaconda3\envs\thesis_2
